# Generated by Django 4.2.25 on 2025-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Message'), ('proposal', 'Proposal'), ('contract', 'Contract'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
