# Generated by Django 4.2.25 on 2025-11-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='proposals.proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('contract', 'reviewer')},
        ),
    ]
